### ISSUE TITLE
Tile bounds computation regression?

### ISSUE THREAD

**Issue by stephanerestani-picterra** [developmentseed/morecantile#164]
We're trying to upgrade from `5.4.2` to `6.0.0` and some of our tests have caught what we believe to be a regression/computation difference(?):
- We're creating a custom `TileMatrixSet` from a known extent+crs (EPSG:2056, Switzerland, see below).
- We're computing the bounds of tile `(0, 0, 0)` on this `TileMatrixSet`.
- We expect these bounds to cover the initial extent.
  - They do in `5.4.2`, but don't in `6.0.0`

Here's what these extents+bounds look like:

| `morecantile==5.4.2` | `morecantile==6.0.0` |
| -------------------- | -------------------- |
| ![image](https://github.com/user-attachments/assets/50608b15-8312-4475-b130-35000de4c791) Bounds (gray) and extents  (yellow) nicely overlap | ![image](https://github.com/user-attachments/assets/d80937cd-a4e0-4077-bff3-a471406f1bdf) Bounds (pink) are offset from the extents (brown) |

Does this behavior reproduce on your end as well? Is it intended / have I misunderstood anything?

Here is the script I used to reproduce this:
```py
import json
import morecantile  # == 6.0.0 (also tested with 6.1.0)
import pyproj  # == 3.7.0

# These extent coordinates are in EPSG:2056 (CH)
extent = [2696082.04374708, 1289407.53195196, 2696210.04374708, 1289535.53195196]
crs = pyproj.CRS.from_epsg("2056")
tms = morecantile.TileMatrixSet.custom(
    extent,
    crs,
)

# I would expect the coordinates of tile (0,0,0) to fully contain the given
# extent, but it doesn't seem to be the case (see screenshot, the two squares
# don't overlap, whereas they do on 5.4.2).
tms_bounds = tms.bounds(0, 0, 0)

# For debugging/viewing purposes, print those as GeoJSON (QGIS should
# be able to open this).
print(json.dumps({
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {},
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [tms_bounds.left, tms_bounds.top],
                    [tms_bounds.left, tms_bounds.bottom],
                    [tms_bounds.right, tms_bounds.bottom],
                    [tms_bounds.right, tms_bounds.top],
                    [tms_bounds.left, tms_bounds.top],
                ]
            ]
        }
    }]
}))

print(json.dumps({
    "type": "FeatureCollection",
    "crs": {
        "type": "name",
        "properties": {
            "name": "epsg:2056"
        }
    },
    "features": [{
        "type": "Feature",
        "properties": {},
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [extent[0], extent[3]],
                    [extent[0], extent[1]],
                    [extent[2], extent[1]],
                    [extent[2], extent[3]],
                    [extent[0], extent[3]],
                ]
            ]
        }
    }]
}))
```

**Comment by vincentsarago** [comment]
I'm pretty sure this is because of https://github.com/developmentseed/morecantile/blob/0ab27a724b762764eaa4c320b2cdf219a7d1d06c/morecantile/models.py#L502-L504

We now try to get the `geographic` CRS from the TMS's CRS directly. I was hopping that for most case the geographic CRS would be `WGS84` for the your CRS it's not 😓 

```python
import pyproj
crs = pyproj.CRS.from_epsg("2056")
print(crs)
>> EPSG:2056

print(crs.geodetic_crs)
>> GEOGCRS["CH1903+",DATUM["CH1903+",ELLIPSOID["Bessel 1841",6377397.155,299.1528128,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],USAGE[SCOPE["Geodesy."],AREA["Liechtenstein; Switzerland."],BBOX[45.82,5.96,47.81,10.49]],ID["EPSG",4150]]

print(tms.geographic_crs.geodetic_crs.to_epsg())
>> 4150
```

```python
extent = [2696082.04374708, 1289407.53195196, 2696210.04374708, 1289535.53195196]
to_geographic = pyproj.Transformer.from_crs(crs, crs.geodetic_crs, always_xy=True)
print(to_geographic.transform_bounds(*extent, densify_pts=21))
>> (8.721008798120367, 47.74957327349827, 8.722743537945185, 47.750743194403526)


wgs84 = pyproj.CRS.from_epsg(4326)
to_wgs84 = pyproj.Transformer.from_crs(crs, wgs84, always_xy=True)
print(to_wgs84.transform_bounds(*extent, densify_pts=21))
>>(8.719843698696495, 47.748167109850456, 8.72157814319208, 47.74933687404682)
```

😭 

SO, the `bounds` method is not WRONG because it gives back result in Geographic CRS BUT it doesn't give back result in WGS84 as it was before!

**Comment by vincentsarago** [comment]
@stephanerestani-picterra can I ask what's your usage of the `tms.bounds` method?

**Comment by vincentsarago** [comment]
@stephanerestani-picterra `tms.bounds` is the `most` expensive operation in morecantile because it involve reprojection of bounds as you know, so in your case it might be better to compare bounds in the TMS's CRS (so reprojecting `aois_index` to the TMS's CRS 

This is what we do in rio-tiler https://github.com/cogeotiff/rio-tiler/blob/main/rio_tiler/io/base.py#L157-L204

you could also compute the intersection of the index and the aoi to remove the need this check.

I'm also realizing that `tms.tiles()` method will assume the bounds to be in the geographic CRS for the TMS which in your case won't be WGS84 😭 (so you'll need to first convert the aois_bbox to the TMS.crs.geographic_crs)

**Comment by stephanerestani-picterra** [comment]
Good points and thanks for the `rio-tiler` pointers! I'll keep this in mind.
