### ISSUE TITLE
Use official TileMatrixSet JSON documents

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/morecantile#3]
Right now we use simple 3 elements (CRS, Extent, scale) to define TileMatrixSet.

https://github.com/developmentseed/morecantile/blob/37382d746cb60400ec90da375600bbcbe184e310/morecantile/__init__.py#L66-L70

But sometimes they can be more complexes e.g https://github.com/OSGeo/gdal/blob/93b48b00b13456f59c84670a9f95d544a1d76748/gdal/data/tms_LINZAntarticaMapTileGrid.json

The main idea is to host the TileMatrixSet as json (found in http://schemas.opengis.net/tms/1.0/json/examples/) and to use each zoom matrice to derive the information we need. 

Note: This will align better with changes added in GDAL 3.2 https://github.com/OSGeo/gdal/pull/2505/files

### Unknown
- Can we use a pydantic model to describe the TileMatrixSet?
- Do we need two classes `TileMatrixSet` (pydantic model) and TileSchema ?
- is `supportedCRS` easily translatable to rasterio CRS? (e.g `http://www.opengis.net/def/crs/EPSG/0/5482`)

**Comment by geospatial-jeff** [comment]
> * is `supportedCRS` easily translatable to rasterio CRS? (e.g `http://www.opengis.net/def/crs/EPSG/0/5482`)

For the most part it is.  If the tile matrix set is defined in EPSG its as simple as `.split('/')[-1]`, but that isn't always the case.  For example. one of the tile matrix sets you have defined in `morecantile/data` is `CRS:84` which is `EPSG:4326` but coordinate order is `lon/lat` instead of `lat/lon` and isn't a part of the EPSG database.

The other way of loading into rasterio CRS is with a pyproj string which would require doing some network requests to find the correct pyproj string.

Maybe we only accept tile matrix sets which are defined in EPSG?  That could be enforced in the pydantic model with a validator.

**Comment by vincentsarago** [comment]
> Maybe we only accept tile matrix sets which are defined in EPSG? That could be enforced in the pydantic model with a validator.

👍 

Can we add a property to the model to return the EPSG number (or the CRS object directly ? )

**Comment by geospatial-jeff** [comment]
> Can we add a property to the model to return the EPSG number (or the CRS object directly ? )

Done in https://github.com/developmentseed/morecantile/pull/6/commits/1a32165b98aa2fbe8230dc1429ec33be6450e448
